heat_template_version: 2013-05-23

description: |
  Heat template to deploy a single server running a PHP app under apache

parameters:

  parent_stack_id:
    description: ID of the parent stack for meta tags
    type: string
    default: "None"

  server_hostname:
    description: Server Name
    type: string
    default: php
    constraints:
    - length:
        min: 1
        max: 64
    - allowed_pattern: "^[a-zA-Z][a-zA-Z0-9-]*$"
      description: |
        Must begin with a letter and contain only alphanumeric characters.

  image:
    description: Server Image
    type: string
    default: Ubuntu 12.04 LTS (Precise Pangolin) (PVHVM)
    constraints:
    - allowed_values:
      - Ubuntu 12.04 LTS (Precise Pangolin) (PVHVM)
      description: Must be a supported operating system.

  flavor:
    description: Rackspace Cloud Server flavor
    type: string
    default: 4 GB General Purpose v1
    constraints:
    - allowed_values:
      - 1 GB General Purpose v1
      - 2 GB General Purpose v1
      - 4 GB General Purpose v1
      - 8 GB General Purpose v1
      - 15 GB I/O v1
      - 30 GB I/O v1
      - 512MB Standard Instance
      - 1GB Standard Instance
      - 2GB Standard Instance
      - 4GB Standard Instance
      - 8GB Standard Instance
      - 15GB Standard Instance
      - 30GB Standard Instance
      description: |
        Must be a valid Rackspace Cloud Server flavor for the region you have
        selected to deploy into.

  ssh_keypair_name:
    description: Nova keypair name for ssh access to the server
    type: string
    default: ''

  revision:
    description: Git Branch/Ref
    type: string
    default: HEAD

  packages:
    description: PHP Packages
    type: string
    default: ''

  repo:
    description: Git Repo URL
    type: string
    default: ''

  url:
    description: URL for site
    type: string
    default: 'http://example.com'

  deploy_key:
    description: Git deploy key for private repositories.
    type: string
    default: ''

  destination:
    description: Deploy Directory
    default: /var/www/vhosts/application
    type: string

  public:
    description: The public facing directory of your application relative to the destination.
    type: string
    default: /

  sslcert:
    description: SSL Certificate
    type: string
    default: false

  sslkey:
    description: SSL Key
    type: string
    default: false

  sslcacert:
    description: SSL CA Certificate
    type: string
    default: false

  # varnish:
  #  description: Install Varnish
  #  type: string
  #  default: false

  http_port:
    description: HTTP Port
    type: string
    default: 80

  https_port:
      description: HTTPS Port
      type: string
      default: 443

  memcached_size:
    description: Memcached memory size limit
    type: number
    default: 128

  private_key:
    description: Private SSH key
    type: string
    default: false

  kitchen:
    description: URL for the kitchen to use
    type: string
    default: https://github.com/rackspace-orchestration-templates/php-app-multi

  chef_version:
    description: Version of chef client to use
    type: string
    default: 11.12.8

resources:

  php_server:
    type: "Rackspace::Cloud::Server"
    properties:
      name: { get_param: server_hostname }
      flavor: { get_param: flavor }
      image: { get_param: image }
      key_name: { get_param: ssh_keypair_name }
      metadata:
        rax-heat: { get_param: parent_stack_id }

  php_setup:
    type: "OS::Heat::ChefSolo"
    depends_on: php_server
    properties:
      username: root
      private_key: { get_param: private_key }
      host: { get_attr: [php_server, accessIPv4] }
      kitchen: { get_param: kitchen }
      chef_version: { get_param: chef_version }
      node:
        php_app:
          destination: { get_param: destination }
          deploy_key: { get_param: deploy_key }
          http_port: { get_param: http_port }
          https_port: { get_param: https_port }
          packages: { get_param: packages }
          public: { get_param: public }
          repo: { get_param: repo }
          rev: { get_param: revision }
          #sslcert: { get_param: sslcert }
          #sslkey: { get_param: sslkey }
          #sslcacert: { get_param: sslcacert }
          url: { get_param: url }
          # varnish: { get_param: varnish }
        memcached:
          listen: 127.0.0.1
        varnish:
          backend_host: 127.0.0.1
        run_list: ["recipe[apt]",
                   "recipe[build-essential]",
                   "recipe[memcached]",
                   "recipe[rax_php_app]",
                   "recipe[php-ioncube]"]

outputs:

  public_ip:
    value: { get_attr: [php_server, accessIPv4] }

  private_ip:
    value: { get_attr: [php_server, privateIPv4]}
