heat_template_version: 2013-05-23

description: |
  Heat template to deploy a load balancer and multiple servers running a PHP app under apache

parameter_groups:

- label: Server Settings
  parameters:
  - image
  - flavor

- label: PHP Application Settings
  parameters:
  - url
  - revision
  - packages
  - repo
  - deploy_key
  - destination
  - public

- label: rax-dev-params
  parameters:
  - child_template
  - load_balancer_hostname
  - server_hostname
  - http_port
  - https_port
  - memcached_size
  - kitchen
  - chef_version


parameters:

  load_balancer_hostname:
    label: Load Balancer Hostname
    description: Hostname for the Load Balancer
    type: string
    default: PHP-Load-Balancer
    constraints:
    - length:
        min: 1
        max: 64
    - allowed_pattern: "^[a-zA-Z][a-zA-Z0-9-]*$"
      description: |
        Must begin with a letter and contain only alphanumeric characters.

  server_hostname:
    label: Server Name
    description: Server Name
    type: string
    default: php
    constraints:
    - length:
        min: 1
        max: 64
    - allowed_pattern: "^[a-zA-Z][a-zA-Z0-9-]*$"
      description: |
        Must begin with a letter and contain only alphanumeric characters.

  server_count:
    label: Server Count
    description: |
      Required: Number of servers to spin up as a part of this deployment.
    type: number
    default: 2
    constraints:
    - range:
        min: 1
        max: 25
      description: Must be between 1 and 25 servers.

  image:
    label: Operating System
    description: |
      Required: Server image used for all servers that are created as a part of
      this deployment.
    type: string
    default: Ubuntu 12.04 LTS (Precise Pangolin) (PVHVM)
    constraints:
    - allowed_values:
      - Ubuntu 12.04 LTS (Precise Pangolin) (PVHVM)
      description: Must be a supported operating system.

  flavor:
    label: Server Size
    description: |
      Required: Rackspace Cloud Server flavor to use. The size is based on the
      amount of RAM for the provisioned server.
    type: string
    default: 4 GB General Purpose v1
    constraints:
    - allowed_values:
      - 1 GB General Purpose v1
      - 2 GB General Purpose v1
      - 4 GB General Purpose v1
      - 8 GB General Purpose v1
      - 15 GB I/O v1
      - 30 GB I/O v1
      - 60 GB I/O v1
      - 90 GB Performance
      - 512MB Standard Instance
      - 1GB Standard Instance
      - 2GB Standard Instance
      - 4GB Standard Instance
      - 8GB Standard Instance
      - 15GB Standard Instance
      - 30GB Standard Instance
      description: |
        Must be a valid Rackspace Cloud Server flavor for the region you have
        selected to deploy into.

  revision:
    label: Revision
    description: |
      Optional: Git Branch/Ref to deploy. Default: HEAD
    type: string
    default: HEAD

  packages:
    label: System Packages
    description: |
      Optional: Additional system packages to install. For a list of available
      packages, see: http://packages.ubuntu.com/precise/allpackages
    type: string
    default: ''

  repo:
    label: Git Repository
    description: |
      Optional: URL to your git repository. Use the https syntax for public
      repositories, use git@ syntax for private repositories.
    type: string
    default: ''

  url:
    label: Site Domain
    description: URL for your site
    type: string
    default: 'http://example.com'

  deploy_key:
    label: Git Deploy Key
    description: |
      Optional: If you specified a private repository, provide your private
      deploy key here.
    type: string
    default: ''

  destination:
    label: Site Path
    description: Path to setup your application on your servers.
    default: /var/www/vhosts/application
    type: string

  public:
    label: Public Directory
    description: |
      The public facing directory of your application relative to the
      destination.
    type: string
    default: /

  # sslcert:
  #  description: SSL Certificate
  #  type: string
  #  default: false

  # sslkey:
  #  description: SSL Key
  #  type: string
  #  default: false

  # sslcacert:
  #  description: SSL CA Certificate
  #  type: string
  #  default: false

  # varnish:
  #  description: Install Varnish
  #  type: string
  #  default: 'false'

  http_port:
    label: HTTP Port
    description: HTTP Port
    type: string
    default: 80

  https_port:
    label: HTTPS Port
    description: HTTPS Port
    type: string
    default: 443

  memcached_size:
    label: Memcached Memory Limit
    description: Memcached memory size limit
    type: number
    default: 128

  kitchen:
    label: Kitchen URL
    description: URL for the kitchen to use
    type: string
    default: https://github.com/rs-randallburt/php-app-multi

  chef_version:
    label: Chef Version
    description: Version of chef client to use
    type: string
    default: 11.12.8

  child_template:
    label: Child Template
    description: Location of child template for provisioning PHP web nodes.
    type: string
    default: https://raw.githubusercontent.com/rs-randallburt/php-app-multi/master/php-app-single.yaml

resources:

  ssh_key:
    type: "OS::Nova::KeyPair"
    properties:
      name: { get_param: "OS::stack_id" }
      save_private_key: true

  php_setup:
    type: "OS::Heat::ResourceGroup"
    properties:
      count: { get_param: server_count }
      resource_def:
        type: { get_param: child_template }
        properties:
          kitchen: { get_param: kitchen }
          chef_version: { get_param: chef_version }
          private_key: { get_attr: [ssh_key, private_key] }
          server_hostname: { get_param: server_hostname }
          image: { get_param: image }
          flavor: { get_param: flavor }
          #sslkey: { get_param: sslkey }
          #sslcert: { get_param: sslcert }
          #sslcacert: { get_param: sslcacert }
          revision: { get_param: revision }
          packages: { get_param: packages }
          repo: { get_param: repo }
          url: { get_param: url }
          deploy_key: { get_param: deploy_key }
          destination: { get_param: destination}
          public: { get_param: public }
          # varnish: { get_param: varnish }
          ssh_keypair_name: { get_resource: ssh_key }
          parent_stack_id: { get_param: "OS::stack_id" }

  load_balancer:
    type: "Rackspace::Cloud::LoadBalancer"
    depends_on:
    - php_setup
    properties:
      name: { get_param: load_balancer_hostname }
      nodes:
      - addresses: { get_attr: [php_setup, private_ip] }
        port: 80
        condition: ENABLED
      healthMonitor:
        type: CONNECT
        delay: 10
        timeout: 5
        attemptsBeforeDeactivation: 1
      port: 80
      protocol: HTTP
      algorithm: ROUND_ROBIN
      contentCaching: ENABLED
      virtualIps:
      - type: PUBLIC
        ipVersion: IPV4
      metadata:
        rax-heat: { get_param: "OS::stack_id" }

outputs:
  private_key:
    description: SSH Private Key
    value: { get_attr: [ssh_key, private_key] }

  load_balancer_ip:
    description: Load Balancer IP
    value: { get_attr: [load_balancer, PublicIp] }

  server_public_ips:
    value: { get_attr: [php_setup, public_ip] }
    description: Server IPs
